name: update paratexts
on:
  repository_dispatch:
    types: [trigger-update]
  workflow_dispatch:
jobs:
  update-paratexts:
    runs-on: ubuntu-latest

    steps:
      - name: cancel previous run
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: |
          cd src
          git clone https://github.com/TST-Project/mss.git
          git clone https://github.com/TST-Project/authority-files.git
          git clone https://github.com/TST-Project/lib.git
          yarn install
          yarn build
          yarn build 2

      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: automatic paratexts update
          file_pattern: ./*.html ./*.xlsx
          commit_user_name: TST[bot]
